/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as CropDoctorRouteImport } from './routes/crop-doctor'
import { Route as MarketRouteImport } from './routes/market'
import { Route as MyFarmRouteImport } from './routes/my-farm'
import { Route as ReportRouteImport } from './routes/report'
import { Route as SchemesRouteImport } from './routes/schemes'
import { Route as WeatherRouteImport } from './routes/weather'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const CropDoctorRoute = CropDoctorRouteImport.update({
  id: '/crop-doctor',
  path: '/crop-doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const MyFarmRoute = MyFarmRouteImport.update({
  id: '/my-farm',
  path: '/my-farm',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const SchemesRoute = SchemesRouteImport.update({
  id: '/schemes',
  path: '/schemes',
  getParentRoute: () => rootRouteImport,
} as any)
const WeatherRoute = WeatherRouteImport.update({
  id: '/weather',
  path: '/weather',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/crop-doctor': typeof CropDoctorRoute
  '/market': typeof MarketRoute
  '/my-farm': typeof MyFarmRoute
  '/report': typeof ReportRoute
  '/schemes': typeof SchemesRoute
  '/weather': typeof WeatherRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/crop-doctor': typeof CropDoctorRoute
  '/market': typeof MarketRoute
  '/my-farm': typeof MyFarmRoute
  '/report': typeof ReportRoute
  '/schemes': typeof SchemesRoute
  '/weather': typeof WeatherRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/crop-doctor': typeof CropDoctorRoute
  '/market': typeof MarketRoute
  '/my-farm': typeof MyFarmRoute
  '/report': typeof ReportRoute
  '/schemes': typeof SchemesRoute
  '/weather': typeof WeatherRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistant'
    | '/crop-doctor'
    | '/market'
    | '/my-farm'
    | '/report'
    | '/schemes'
    | '/weather'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistant'
    | '/crop-doctor'
    | '/market'
    | '/my-farm'
    | '/report'
    | '/schemes'
    | '/weather'
  id:
    | '__root__'
    | '/'
    | '/assistant'
    | '/crop-doctor'
    | '/market'
    | '/my-farm'
    | '/report'
    | '/schemes'
    | '/weather'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistantRoute: typeof AssistantRoute
  CropDoctorRoute: typeof CropDoctorRoute
  MarketRoute: typeof MarketRoute
  MyFarmRoute: typeof MyFarmRoute
  ReportRoute: typeof ReportRoute
  SchemesRoute: typeof SchemesRoute
  WeatherRoute: typeof WeatherRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crop-doctor': {
      id: '/crop-doctor'
      path: '/crop-doctor'
      fullPath: '/crop-doctor'
      preLoaderRoute: typeof CropDoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-farm': {
      id: '/my-farm'
      path: '/my-farm'
      fullPath: '/my-farm'
      preLoaderRoute: typeof MyFarmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schemes': {
      id: '/schemes'
      path: '/schemes'
      fullPath: '/schemes'
      preLoaderRoute: typeof SchemesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weather': {
      id: '/weather'
      path: '/weather'
      fullPath: '/weather'
      preLoaderRoute: typeof WeatherRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistantRoute: AssistantRoute,
  CropDoctorRoute: CropDoctorRoute,
  MarketRoute: MarketRoute,
  MyFarmRoute: MyFarmRoute,
  ReportRoute: ReportRoute,
  SchemesRoute: SchemesRoute,
  WeatherRoute: WeatherRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
